name: tutorial_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets: 
    - assets/images/lauterbrunnen.jpg
    - assets/images/logo.svg

  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Schyler-Regular.ttf




